#pragma once

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 0
#define APP_VERSION_PATCH 3
#define APP_VERSION_BUILD 0

#define APP_VERSION_COMMA 1,0,3,0
#define APP_VERSION_STRING "1.03"
#define APP_VERSION_WSTRING L"1.03"
